<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the Batch connector object
 *
 */
trait BatchDefinition
{    

	 /**
	 * @var Array
	 *
	 
	 */
	
	private $operations;
	
    

	
	/**
	 * Add elem
	 * @param mixed $elem
	 * @return Batch
	 */
	public function addOperations($elem)
	{
		$this->operations[] = $elem;
		return $this;
	}

	/**
	 * Has elem
	 * @param mixed $elem
	 * @return boolean
	 */
	public function hasOperations($elem)
	{
		return in_array($elem, $this->operations);
	}
	
	
	/**
	 * Get operations
	 *
	 * @return Array
	 */
	public function getOperations()
	{
		return $this->operations;
	}

	/**
	 * Set operations
	 *
	 * @param  Array $operations
	 * @return Batch
	 */
	public function setOperations($operations)
	{
		$this->operations = $operations;
		
		return $this;
	}	
}