<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the CampaignDefaults connector object
 *
 */
trait CampaignDefaultsDefinition
{    


	private $fromName;    


	private $fromEmail;    


	private $subject;    


	private $language;    

	public function setFromName($fromName)
	{
		$this->fromName = $fromName;
		
		return $this;
	}
	
	public function getFromName()
	{
		return $this->fromName;
	}
    

	public function setFromEmail($fromEmail)
	{
		$this->fromEmail = $fromEmail;
		
		return $this;
	}
	
	public function getFromEmail()
	{
		return $this->fromEmail;
	}
    

	public function setSubject($subject)
	{
		$this->subject = $subject;
		
		return $this;
	}
	
	public function getSubject()
	{
		return $this->subject;
	}
    

	public function setLanguage($language)
	{
		$this->language = $language;
		
		return $this;
	}
	
	public function getLanguage()
	{
		return $this->language;
	}
}