<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the Contact connector object
 *
 */
trait ContactDefinition
{    


	private $company;    


	private $address1;    


	private $address2;    


	private $city;    


	private $state;    


	private $zip;    


	private $country;    


	private $phone;    

	public function setCompany($company)
	{
		$this->company = $company;
		
		return $this;
	}
	
	public function getCompany()
	{
		return $this->company;
	}
    

	public function setAddress1($address1)
	{
		$this->address1 = $address1;
		
		return $this;
	}
	
	public function getAddress1()
	{
		return $this->address1;
	}
    

	public function setAddress2($address2)
	{
		$this->address2 = $address2;
		
		return $this;
	}
	
	public function getAddress2()
	{
		return $this->address2;
	}
    

	public function setCity($city)
	{
		$this->city = $city;
		
		return $this;
	}
	
	public function getCity()
	{
		return $this->city;
	}
    

	public function setState($state)
	{
		$this->state = $state;
		
		return $this;
	}
	
	public function getState()
	{
		return $this->state;
	}
    

	public function setZip($zip)
	{
		$this->zip = $zip;
		
		return $this;
	}
	
	public function getZip()
	{
		return $this->zip;
	}
    

	public function setCountry($country)
	{
		$this->country = $country;
		
		return $this;
	}
	
	public function getCountry()
	{
		return $this->country;
	}
    

	public function setPhone($phone)
	{
		$this->phone = $phone;
		
		return $this;
	}
	
	public function getPhone()
	{
		return $this->phone;
	}
}