<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the File connector object
 *
 */
trait FileDefinition
{    

	 /**
	 * @var integer
	 *
	 */
	private $folderId;
    

	 /**
	 * @var string
	 *
	 */
	private $name;
    

	 /**
	 * @var string
	 *
	 */
	private $fileData;
    

	
	/**
	 * Get folderId
	 *
	 * @return integer
	 */
	public function getFolderId()
	{
		return $this->folderId;
	}

	/**
	 * Set folderId
	 *
	 * @param  integer $folderId
	 * @return File
	 */
	public function setFolderId($folderId)
	{
		$this->folderId = $folderId;
		
		return $this;
	}
    

	
	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param  string $name
	 * @return File
	 */
	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}
    

	
	/**
	 * Get fileData
	 *
	 * @return string
	 */
	public function getFileData()
	{
		return $this->fileData;
	}

	/**
	 * Set fileData
	 *
	 * @param  string $fileData
	 * @return File
	 */
	public function setFileData($fileData)
	{
		$this->fileData = $fileData;
		
		return $this;
	}
}