<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the List connector object
 *
 */
trait ListDefinition
{    


	private $id;    


	private $name;    


	private $contact;    


	private $permissionReminder;    


	private $useArchiveBar;    


	private $campaignDefaults;    


	private $notifyOnSubscribe;    


	private $notifyOnUnsubscribe;    


	private $dateCreated;    


	private $listRating;    


	private $emailTypeOption;    


	private $subscribeUrlShort;    


	private $subscribeUrlLong;    


	private $beamerAddress;    


	private $visibility;    

	public function setId($id)
	{
		$this->id = $id;
		
		return $this;
	}
	
	public function getId()
	{
		return $this->id;
	}
    

	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}
	
	public function getName()
	{
		return $this->name;
	}
    

	public function setContact($contact)
	{
		$this->contact = $contact;
		
		return $this;
	}
	
	public function getContact()
	{
		return $this->contact;
	}
    

	public function setPermissionReminder($permissionReminder)
	{
		$this->permissionReminder = $permissionReminder;
		
		return $this;
	}
	
	public function getPermissionReminder()
	{
		return $this->permissionReminder;
	}
    

	public function setUseArchiveBar($useArchiveBar)
	{
		$this->useArchiveBar = $useArchiveBar;
		
		return $this;
	}
	
	public function getUseArchiveBar()
	{
		return $this->useArchiveBar;
	}
    

	public function setCampaignDefaults($campaignDefaults)
	{
		$this->campaignDefaults = $campaignDefaults;
		
		return $this;
	}
	
	public function getCampaignDefaults()
	{
		return $this->campaignDefaults;
	}
    

	public function setNotifyOnSubscribe($notifyOnSubscribe)
	{
		$this->notifyOnSubscribe = $notifyOnSubscribe;
		
		return $this;
	}
	
	public function getNotifyOnSubscribe()
	{
		return $this->notifyOnSubscribe;
	}
    

	public function setNotifyOnUnsubscribe($notifyOnUnsubscribe)
	{
		$this->notifyOnUnsubscribe = $notifyOnUnsubscribe;
		
		return $this;
	}
	
	public function getNotifyOnUnsubscribe()
	{
		return $this->notifyOnUnsubscribe;
	}
    

	public function setDateCreated($dateCreated)
	{
		$this->dateCreated = $dateCreated;
		
		return $this;
	}
	
	public function getDateCreated()
	{
		return $this->dateCreated;
	}
    

	public function setListRating($listRating)
	{
		$this->listRating = $listRating;
		
		return $this;
	}
	
	public function getListRating()
	{
		return $this->listRating;
	}
    

	public function setEmailTypeOption($emailTypeOption)
	{
		$this->emailTypeOption = $emailTypeOption;
		
		return $this;
	}
	
	public function getEmailTypeOption()
	{
		return $this->emailTypeOption;
	}
    

	public function setSubscribeUrlShort($subscribeUrlShort)
	{
		$this->subscribeUrlShort = $subscribeUrlShort;
		
		return $this;
	}
	
	public function getSubscribeUrlShort()
	{
		return $this->subscribeUrlShort;
	}
    

	public function setSubscribeUrlLong($subscribeUrlLong)
	{
		$this->subscribeUrlLong = $subscribeUrlLong;
		
		return $this;
	}
	
	public function getSubscribeUrlLong()
	{
		return $this->subscribeUrlLong;
	}
    

	public function setBeamerAddress($beamerAddress)
	{
		$this->beamerAddress = $beamerAddress;
		
		return $this;
	}
	
	public function getBeamerAddress()
	{
		return $this->beamerAddress;
	}
    

	public function setVisibility($visibility)
	{
		$this->visibility = $visibility;
		
		return $this;
	}
	
	public function getVisibility()
	{
		return $this->visibility;
	}
}