<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the Template-folder connector object
 *
 */
trait Template-folderDefinition
{    

	 /**
	 * @var string
	 *
	 */
	private $name;
    

	
	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param  string $name
	 * @return Template-folder
	 */
	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}
}