<?php
/**
 * This file is autogenerated. All changes done in this file will be lost.
 */

namespace MailChimpBundle\Entity\Definition;

/**
 * Definition class for the Template connector object
 *
 */
trait TemplateDefinition
{    

	 /**
	 * @var string
	 *
	 */
	private $name;
    

	 /**
	 * @var string
	 *
	 */
	private $folderId;
    

	 /**
	 * @var string
	 *
	 */
	private $html;
    

	
	/**
	 * Get name
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set name
	 *
	 * @param  string $name
	 * @return Template
	 */
	public function setName($name)
	{
		$this->name = $name;
		
		return $this;
	}
    

	
	/**
	 * Get folderId
	 *
	 * @return string
	 */
	public function getFolderId()
	{
		return $this->folderId;
	}

	/**
	 * Set folderId
	 *
	 * @param  string $folderId
	 * @return Template
	 */
	public function setFolderId($folderId)
	{
		$this->folderId = $folderId;
		
		return $this;
	}
    

	
	/**
	 * Get html
	 *
	 * @return string
	 */
	public function getHtml()
	{
		return $this->html;
	}

	/**
	 * Set html
	 *
	 * @param  string $html
	 * @return Template
	 */
	public function setHtml($html)
	{
		$this->html = $html;
		
		return $this;
	}
}